"""empty message

Revision ID: 2397e5374e6f
Revises: f108cdf72f36
Create Date: 2023-07-17 08:41:20.609205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2397e5374e6f'
down_revision = 'f108cdf72f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_logic_delete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_silent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_column('is_silent')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('is_logic_delete')

    # ### end Alembic commands ###
