"""empty message

Revision ID: 4da394cfb54e
Revises: 0c1aaa267bc3
Create Date: 2023-07-14 16:11:22.731697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da394cfb54e'
down_revision = '0c1aaa267bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.alter_column('avator',
               existing_type=sa.BLOB(),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.alter_column('avator',
               existing_type=sa.String(length=256),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
