"""empty message

Revision ID: 518acbc9de0e
Revises: 
Create Date: 2023-07-11 20:26:14.153953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518acbc9de0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_column('permission')

    # ### end Alembic commands ###
