"""empty message

Revision ID: ba0e4b1079dd
Revises: f357a9c62f0a
Create Date: 2023-07-10 16:51:49.131483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba0e4b1079dd'
down_revision = 'f357a9c62f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_time')
        batch_op.drop_column('created_time')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_time')
        batch_op.drop_column('created_time')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_time')
        batch_op.drop_column('created_time')

    # ### end Alembic commands ###
