"""empty message

Revision ID: f357a9c62f0a
Revises: a4b3361dd470
Create Date: 2023-07-10 15:41:36.809167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f357a9c62f0a'
down_revision = 'a4b3361dd470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('create_time')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('active')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
